project:
  type: website
  output-dir: docs

website:
  title: "LABDATA"
  sidebar:
    search: true
    logo: https://ence.ibge.gov.br/images/logoence.fw.png
    contents:
      - href: index.qmd
        text: "Introdução"
      - section: "Tabela 6471 - Rendimento médio"
        contents: 
          - tabela6471.qmd
          - grafico6471.qmd
          - mapa6471.qmd
      - section: "Tabela 5606 - Massa de rendimento"
        contents: 
          - tabela5606.qmd
          - grafico5606.qmd
      - section: "Tabela 5917 - População total"
        contents: 
          - tabela5917.qmd
          - grafico5917.qmd
      - section: "Tabela 4099 - Taxa de desocupação"
        contents: 
          - tabela4099.qmd
          - grafico4099.qmd
      - section: "Tabela 6371 - Média de horas habitualmente trabalhada"
        contents: 
          - tabela6371.qmd
          - grafico6371.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
